name: Build CmusicAI for macOS

on:
  workflow_dispatch:
    inputs:
      target:
        description: 'Target branch to run'
        required: true
      version:
        description: 'Version that will be built'
        required: true

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang cmake autoconf automake libtool curl make gawk

      - name: Install SDKs and Toolchain
        run: |
          mkdir -p depends/SDKs
          cd depends/SDKs
          curl -O https://bitcoincore.org/depends-sources/sdks/Xcode-11.3.1-11C505-extracted-SDK-with-libcxx-headers.tar.gz
          tar -zxf Xcode-11.3.1-11C505-extracted-SDK-with-libcxx-headers.tar.gz

      - name: Install Berkeley DB
        run: |
          chmod +x depends/packages/00-berkeley-db.sh
          depends/packages/00-berkeley-db.sh osx

      - name: Export Paths
        run: |
          export PATH=${GITHUB_WORKSPACE}/depends/x86_64-apple-darwin14/native/bin:$PATH

      - name: Prepare Build Environment
        run: |
          cd ${GITHUB_WORKSPACE}
          if [ ! -f ./configure ]; then
            echo "Generating configure script"
            ./autogen.sh
          fi

      - name: Configure Build
        run: |
          set -x
          cd ${GITHUB_WORKSPACE}
          export BDB_PREFIX=${GITHUB_WORKSPACE}/depends/SDKs/db-4.8.30.NC
          CONFIG_SITE=${GITHUB_WORKSPACE}/depends/x86_64-apple-darwin14/share/config.site \
          CPPFLAGS="-I${BDB_PREFIX}/include" \
          LDFLAGS="-L${BDB_PREFIX}/lib" \
          ./configure --prefix=/ --disable-ccache --disable-maintainer-mode --disable-dependency-tracking --enable-reduce-exports --disable-bench --disable-gui-tests GENISOIMAGE=${GITHUB_WORKSPACE}/depends/x86_64-apple-darwin14/native/bin/genisoimage

      - name: Build
        run: |
          make -j$(nproc)

      - name: Package
        run: |
          mkdir -p release
          tar -czvf release/cmusicai-${{ github.sha }}-macos.tar.gz src/cmusicaid src/cmusicai-cli src/qt/cmusicai-qt

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: cmusicai-macos
          path: release/*.tar.gz

      - name: Upload config.log
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: config-log
          path: /home/runner/work/Cmusic/Cmusic/depends/work/build/x86_64-apple-darwin14/native_cctools/*/cctools/config.log
